backend:
  name: github
  repo: jo2/dutch-cookbook-data

media_folder: static/assets
public_folder: /assets

collections:
  - name: recipes
    label: Recpies
    folder: recipes
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: author, label: Auhtor }
      - { name: spice, label: Spice }
      - { name: slug, label: Slug }
  - name: spices
    label: Spices
    folder: spices
    create: true
    fields:
      - { name: path, label: Path }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: author, label: Auhtor }
      - { name: slug, label: Slug }
