backend:
  name: github
  repo: jo2/dutch-cookbook

media_folder: _data/assets
public_folder: /assets

collections:
  - name: recipes
    label: Recipes
    folder: "_data/recipes"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "image", label: "Image", widget: "image" }
      - { name: "body", label: "Body", widget: "markdown" }
      - { name: "spice", label: "Spice", widget: "string" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "ingredients", label: "Ingredients", widget: "list", summary: '{{fields.ingredient}}', field:
          { label: "Ingredient", name: "ingredient", widget: "string" }
        }
      - { name: "slug", label: "Slug", widget: "string" }
  - name: spices
    label: Spices
    folder: "_data/spices"
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Title", widget: "string" }
      - { name: "ingredients", label: "Ingredients", widget: "list" }
      - { name: "author", label: "Author", widget: "string" }
      - { name: "slug", label: "Slug", widget: "string" }
